service: auth-lambda
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-central-1
  apiGateway:
    shouldStartNameWithService: true

package:
  patterns:
    - '!/**'
    - dist/**
    - node_modules/**

plugins:
  - serverless-offline

functions:
  api:
    handler: dist/handler.handler
    events:
      - http:
          path: example
          method: any
          cors: true
